
service: my-server

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
resources:
  Resources:
    MyS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: my-s3-bucket
functions:
  hello:
    handler: handler.hello


plugins:
  - serverless-python-requirements
